import type { Product } from "./types/productData";

export const products: Product[] = [
    {
        id: 1,
        name: "Essential Silver Band",
        gender: "men",
        price: 299,
        description: "",
        images: [],
        material: "Stainless Steel",
        rating: 4.6,
        stock: 24,
        sizes: ["7", "8", "9", "10", "11", "12"]
    },
    {
        id: 2,
        name: "Black Textured Signet Ring",
        gender: "men",
        price: 349,
        description: "",
        images: [],
        material: "Stainless Steel",
        rating: 4.8,
        stock: 17,
        sizes: ["8", "9", "10", "11", "12"]
    },
    {
        id: 3,
        name: "Geometric Contrast Ring",
        gender: "men",
        price: 399,
        description: "",
        images: [],
        material: "Stainless Steel",
        rating: 4.4,
        stock: 31,
        sizes: ["7", "8", "9", "10", "11"]
    },
    {
        id: 4,
        name: "Classic Steel Chain",
        gender: "men",
        price: 449,
        description: "",
        images: [],
        material: "Stainless Steel",
        rating: 4.7,
        stock: 19,
        sizes: ["50cm", "55cm", "60cm"]
    },
    {
        id: 5,
        name: "Black Pendant Necklace",
        gender: "men",
        price: 379,
        description: "",
        images: [],
        material: "Stainless Steel",
        rating: 4.5,
        stock: 28,
        sizes: ["50cm", "55cm", "60cm"]
    },
    {
        id: 6,
        name: "Layered Silver Necklace",
        gender: "men",
        price: 499,
        description: "",
        images: [],
        material: "Stainless Steel",
        rating: 4.9,
        stock: 12,
        sizes: ["50cm", "55cm", "60cm"]
    },
    {
        id: 7,
        name: "Minimal Steel Cuff",
        gender: "men",
        price: 329,
        description: "",
        images: [],
        material: "Stainless Steel",
        rating: 4.6,
        stock: 22,
        sizes: ["S", "M", "L"]
    },
    {
        id: 8,
        name: "Leather Metal Bracelet",
        gender: "men",
        price: 299,
        description: "",
        images: [],
        material: "Leather & Stainless Steel",
        rating: 4.3,
        stock: 35,
        sizes: ["S", "M", "L"]
    },
    {
        id: 9,
        name: "Everyday Black Watch",
        gender: "men",
        price: 899,
        description: "",
        images: [],
        material: "Stainless Steel & Mineral Glass",
        rating: 4.7,
        stock: 14,
        sizes: ["One Size"]
    },
    {
        id: 10,
        name: "Silver Chronograph Watch",
        gender: "men",
        price: 1199,
        description: "",
        images: [],
        material: "Stainless Steel & Mineral Glass",
        rating: 4.8,
        stock: 9,
        sizes: ["One Size"]
    },
    {
        id: 11,
        name: "Delicate Gold Ring",
        gender: "women",
        price: 299,
        description: "",
        images: [],
        material: "Stainless Steel",
        rating: 4.7,
        stock: 26,
        sizes: ["5", "6", "7", "8", "9"]
    },
    {
        id: 12,
        name: "Pearl Accent Ring",
        gender: "women",
        price: 349,
        description: "",
        images: [],
        material: "Stainless Steel & Pearl",
        rating: 4.8,
        stock: 18,
        sizes: ["5", "6", "7", "8", "9"]
    },
    {
        id: 13,
        name: "Twisted Silver Ring",
        gender: "women",
        price: 279,
        description: "",
        images: [],
        material: "Sterling Silver",
        rating: 4.5,
        stock: 32,
        sizes: ["5", "6", "7", "8", "9"]
    },
    {
        id: 14,
        name: "Fine Gold Chain Necklace",
        gender: "women",
        price: 399,
        description: "",
        images: [],
        material: "Stainless Steel",
        rating: 4.6,
        stock: 21,
        sizes: ["40cm", "45cm", "50cm"]
    },
    {
        id: 15,
        name: "Heart Pendant Necklace",
        gender: "women",
        price: 329,
        description: "",
        images: [],
        material: "Stainless Steel",
        rating: 4.4,
        stock: 29,
        sizes: ["40cm", "45cm", "50cm"]
    },
    {
        id: 16,
        name: "Pearl Layered Necklace",
        gender: "women",
        price: 549,
        description: "",
        images: [],
        material: "Stainless Steel & Freshwater Pearl",
        rating: 4.9,
        stock: 11,
        sizes: ["40cm", "45cm", "50cm"]
    },
    {
        id: 17,
        name: "Slim Gold Bracelet",
        gender: "women",
        price: 299,
        description: "",
        images: [],
        material: "Stainless Steel",
        rating: 4.7,
        stock: 24,
        sizes: ["S", "M", "L"]
    },
    {
        id: 18,
        name: "Delicate Charm Bracelet",
        gender: "women",
        price: 379,
        description: "",
        images: [],
        material: "Stainless Steel",
        rating: 4.5,
        stock: 20,
        sizes: ["S", "M", "L"]
    },
    {
        id: 19,
        name: "Classic Gold Watch",
        gender: "women",
        price: 899,
        description: "",
        images: [],
        material: "Stainless Steel & Mineral Glass",
        rating: 4.6,
        stock: 13,
        sizes: ["One Size"]
    },
    {
        id: 20,
        name: "Rose Gold Watch",
        gender: "women",
        price: 1099,
        description: "",
        images: [],
        material: "Stainless Steel & Mineral Glass",
        rating: 4.8,
        stock: 8,
        sizes: ["One Size"]
    },
    {
        id: 21,
        name: "Classic Silver Band",
        gender: "unisex",
        price: 299,
        description: "",
        images: [],
        material: "Stainless Steel",
        rating: 4.7,
        stock: 27,
        sizes: ["6", "7", "8", "9", "10", "11", "12"]
    },
    {
        id: 22,
        name: "Black Minimal Ring",
        gender: "unisex",
        price: 329,
        description: "",
        images: [],
        material: "Stainless Steel",
        rating: 4.5,
        stock: 23,
        sizes: ["6", "7", "8", "9", "10", "11", "12"]
    },
    {
        id: 23,
        name: "Silver Chain Necklace",
        gender: "unisex",
        price: 399,
        description: "",
        images: [],
        material: "Stainless Steel",
        rating: 4.8,
        stock: 18,
        sizes: ["45cm", "50cm", "55cm", "60cm"]
    },
    {
        id: 24,
        name: "Black Pendant Necklace",
        gender: "unisex",
        price: 379,
        description: "",
        images: [],
        material: "Stainless Steel",
        rating: 4.6,
        stock: 25,
        sizes: ["45cm", "50cm", "55cm", "60cm"]
    },
    {
        id: 25,
        name: "Textured Steel Bracelet",
        gender: "unisex",
        price: 349,
        description: "",
        images: [],
        material: "Stainless Steel",
        rating: 4.4,
        stock: 31,
        sizes: ["S", "M", "L"]
    },
    {
        id: 26,
        name: "Braided Leather Bracelet",
        gender: "unisex",
        price: 299,
        description: "",
        images: [],
        material: "Leather & Stainless Steel",
        rating: 4.7,
        stock: 34,
        sizes: ["S", "M", "L"]
    },
    {
        id: 27,
        name: "Minimal Steel Cuff",
        gender: "unisex",
        price: 329,
        description: "",
        images: [],
        material: "Stainless Steel",
        rating: 4.8,
        stock: 16,
        sizes: ["S", "M", "L"]
    },
    {
        id: 28,
        name: "Classic Leather Watch",
        gender: "unisex",
        price: 799,
        description: "",
        images: [],
        material: "Leather & Stainless Steel",
        rating: 4.5,
        stock: 15,
        sizes: ["One Size"]
    },
    {
        id: 29,
        name: "Silver Mesh Watch",
        gender: "unisex",
        price: 999,
        description: "",
        images: [],
        material: "Stainless Steel & Mineral Glass",
        rating: 4.9,
        stock: 10,
        sizes: ["One Size"]
    },
    {
        id: 30,
        name: "Matte Black Watch",
        gender: "unisex",
        price: 899,
        description: "",
        images: [],
        material: "Stainless Steel & Mineral Glass",
        rating: 4.6,
        stock: 12,
        sizes: ["One Size"]
    }
]